# Generated by Django 5.0.2 on 2024-02-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_studysphereuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysphereuser',
            name='date_of_birth',
        ),
    ]
