# Generated by Django 5.0.2 on 2024-02-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_studysphereuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysphereuser',
            name='first_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studysphereuser',
            name='last_name',
            field=models.TextField(max_length=20),
        ),
    ]
