# Generated by Django 5.0.2 on 2024-02-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banner_image',
            field=models.FileField(default='default_profile.jpg', upload_to='course_banners'),
        ),
    ]
