# Generated by Django 5.0.2 on 2024-02-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursecontent_deadline_coursedeadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='deadline',
        ),
    ]
