# Generated by Django 5.0.2 on 2024-03-01 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_notificationcontent_notificationenroll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationenroll',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationenroll',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
